article/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "article"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/', views.articles, name = "articles"),
    path('article/<slug:article_slug>', views.article_detail, name="articleDetail")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls'))
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from unidecode import unidecode

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length = 50, verbose_name="Başlık")
    content = RichTextField(('Makale İçeriği'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    article_slug = models.SlugField(unique= True, default='defaultVal')
    article_meta_description = models.CharField(('Makale Meta Açıklaması'), max_length= 250, default= 'default meta acıklaması')

    KATEGORILER = (
        ('Mobil Uygulamar', 'Mobil Uygulamalar'),
        ('Web Tasarımları', 'Web Tasarımları'),
        ('Reklam Hizmetleri', 'Reklam Hizmetleri'),
    )

    article_kategori = models.CharField(('Makale Kategorisi'), max_length=50, choices=KATEGORILER, default= 'websitesi')

    def __str__(self):
        return self.title

    class Meta:
        ordering= ('-created_date',)
        verbose_name = 'Makale'
        verbose_name_plural = 'Makaleler'

    def save(self, *args, **kwargs):
        self.article_slug = slugify(unidecode(self.title))
        super(Article, self).save(*args, **kwargs)

article/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

def articles(request):
    articles = Article.objects.all()
    paginator = Paginator(articles,6)
    page = request.GET.get('page')
    makale = paginator.get_page(page)
    return render(request, "articles.html", {'makale' : makale})


def article_detail(request, articleslug):
    article = Article.objects.get(article_slug=articleslug)
    return render(request, "article_detail.html",{'nbar' : 'article_detail','article': article})

article/templates/about.html
{% extends 'layout.html' %}
{% load static %}


{% block content%}

    <!-- Header -->
    <header class="header text-white" style="background-image: url(/static/assets/img/thumb/14.jpg)">
      <div class="overlay opacity-75" style="background-image: linear-gradient(to top, #0d8464 0%, #4c8bb1 100%);"></div>
      <div class="container text-center">

        <div class="row">
          <div class="col-md-8 mx-auto py-8">
            <h1 class="display-41">Girişimlerinizi Güçlü Bir Web Sitesi İle Onurlandırın</h1>
            <p class="lead-2 opacity-901 mt-6">Güçlü Ve Estetik Bir Web Tasarımı Bizim İçin Bir Tutku</p>

          </div>
        </div>

      </div>
    </header><!-- /.header -->
    <!-- Main Content -->
    <main class="main-content">



      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Our Mission
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <section class="section">
        <div class="container">
          <div class="row gap-y align-items-center">

            <div class="col-md-8 mx-auto">
              <h2>Hakkımızda</h2>
              <p class="lead">Biz yaratıcı ve deneyimli tasarımcı ve geliştiricilerden oluşan bir ekibiz. Eskiden freelancer olarak çalıştığımızdan ötürü neye ihtiyacın olduğunu biliyoruz ve dahası, müşterilerinizin sizden ne istediğini biliyoruz. </p>
              <p> Herkes neden yeni bir ortak dilin arzu edilmesinin istendiğini anlar: pahalı tercümanlara ödeme yapmayı reddedebilir. Bunu başarmak için düzgün dilbilgisi, telaffuz ve daha yaygın kelimeler olması gerekir. </p>
              <p> Birkaç dil birleştiğinde, ortaya çıkan dilin dilbilgisi bireysel dillerden daha basit ve düzenlidir. Yeni ortak dil, mevcut Avrupa dillerinden daha basit ve düzenli olacak. Bizim Web sitelerimiz basit bir dille kompleks bir yapı benimser.</p>

            </div>

          </div>
        </div>
      </section>


      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Numbers
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <section class="section bg-gray">
        <div class="container">
          <div class="row gap-y">

            <div class="col-md-4">
              <div class="row">
                <div class="col-6">
                  <h4 class="lead-7 text-right" data-provide="countup" data-from="0" data-to="42"></h4>
                </div>

                <div class="col-6">
                  <p class="small text-uppercase ls-2 mb-2">Projeler</p>
                  <p><i class="icon-briefcase lead-4 mb-0"></i></p>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="row">
                <div class="col-6">
                  <h4 class="lead-7 text-right" data-provide="countup" data-from="0" data-to="3500"></h4>
                </div>

                <div class="col-6">
                  <p class="small text-uppercase ls-2 mb-2">Müşteriler</p>
                  <p><i class="icon-profile-male lead-4 mb-0"></i></p>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="row">
                <div class="col-6">
                  <h4 class="lead-7 text-right" data-provide="countup" data-from="0" data-to="100" data-prefix="%"></h4>
                </div>

                <div class="col-6">
                  <p class="small text-uppercase ls-2 mb-2">Memnuniyet</p>
                  <p><i class="icon-happy lead-4 mb-0"></i></p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>


      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Services
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <section class="section">
        <div class="container">
          <header class="section-header">
            <small>Yardım Servisi</small>
            <h2>Yardıma İhtiyacın Varsa</h2>
            <hr>
            <p class="lead">Takımınıza aşağıdaki şekillerde yardımcı olabiliriz. Daha fazla bilgi için bizimle iletişime geçmekten çekinmeyin.</p>
          </header>


          <div class="row gap-y">

            <div class="col-md-6 col-xl-4">
              <div class="text-center">
                <p class="mb-6"><i class="icon-tools text-primary lead-8"></i></p>
                <h5><strong>Marka & Tasarım </strong></h5>
                <p>Web sayfalarınız, masaüstü, tablet ve mobil dahil tüm cihazlarda ve ekran boyutlarında iyi görünür.</p>
              </div>
            </div>

            <div class="col-md-6 col-xl-4">
              <div class="text-center">
                <p class="mb-6"><i class="icon-mobile text-primary lead-8"></i></p>
                <h5><strong>Mobil Uygulamalar</strong></h5>
                <p>Web sayfalarınız, masaüstü, tablet ve mobil dahil tüm cihazlarda ve ekran boyutlarında iyi görünür.</p>
              </div>
            </div>

            <div class="col-md-6 col-xl-4">
              <div class="text-center">
                <p class="mb-6"><i class="icon-browser text-primary lead-8"></i></p>
                <h5><strong>Web Uygulamaları</strong></h5>
                <p>Web sayfalarınız, masaüstü, tablet ve mobil dahil tüm cihazlarda ve ekran boyutlarında iyi görünür.</p>
              </div>
            </div>

          </div>


        </div>
      </section>



      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Team
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <section class="section">
        <div class="container">
          <header class="section-header">
            <small>Çalışanlarımız</small>
            <h2>Muhteşem Ekip</h2>
            <hr>
            <p class="lead">Meet our small team that make those great products.</p>
          </header>

          <div class="row d-flex justify-content-center">
            <div class="col-md-4 team-2">
              <a href="#">
                <img src= "{% static '/assets/img/avatar/1.jpg' %}" alt="...">
              </a>
              <h5>Arınç Aslan</h5>
              <small>Co-Founder & Web Tasarımcısı</small>

              <br>
              <div class="social social-brand">
                <a class="social-facebook" href="#"><i class="fa fa-facebook"></i></a>
                <a class="social-twitter" href="#"><i class="fa fa-twitter"></i></a>
                <a class="social-gplus" href="#"><i class="fa fa-google-plus"></i></a>
                <a class="social-linkedin" href="#"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>


            <div class="col-md-4 team-2">
              <a href="#">
                <img src= "{% static '/assets/img/avatar/2.jpg' %}" alt="...">
              </a>
              <h5>Berk Elmas</h5>
              <small>Co-Founder & Web Tasarımcısı</small>

              <br>
              <div class="social social-brand">
                <a class="social-facebook" href="#"><i class="fa fa-facebook"></i></a>
                <a class="social-twitter" href="#"><i class="fa fa-twitter"></i></a>
                <a class="social-gplus" href="#"><i class="fa fa-google-plus"></i></a>
                <a class="social-linkedin" href="#"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>


          </div>

        </div>
      </section>

{% endblock %}

article/templates/article_detail.html
{% extends "layout.html" %}
{% load static %}

{% block content %}


    <!-- Main Content -->
    <main class="main-content">


      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Blog content
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <div class="section" id="section-content">
        <div class="container">

          <div class="row">
            <div class="col-lg-8 mx-auto">

              <p class="lead">Worthy all math at of they these a to beings think and she in he I to off poetic not these little of big and one eminent should, sides behave. Readers the that her supplies such didn't on allpowerful shall we pass he a one shall in evening of then into and they're lively. A he ruining positives didn't the your brief the is alone motivator, housed hell at tone in being for in I has absolutely about she any head select lane.</p>

              <hr class="w-100px">

              <p>Distant I rationale real in text, was chest the and copy pouring death, curiously, to once turned they place his that trying. At harmonics; Quite to understood. Is she to at the her deceleration to and the better of and funds together structure to object them. Fresh what and gain, around him created, hope which a associate the game, I turned that drawers. Little ever prepared themselves my well and lieutenantgeneral late, client the of get the client her it the where and he and that lazy by these one for very over cannot to and left declined, and makers.</p>

              <p>A then low win variety own this every real all the salesman be I don't thin it if bed in anchors slowly he you have I young picture same the your own absolutely question everyday. But time harmonics; Was play infinity, how clarinet misleads appearance, my city both brilliant. Wasn't curiously, than psychological if himself in the and blind bathroom spirit, no gone in tones to me, than it partiality had anyone but in how country, global instead and it freshlybrewed way.</p>

            </div>
          </div>



          <div class="text-center my-6">
            <img class="rounded-md" src="{% static '/assets/img/bg/11.jpg' %}" alt="...">
          </div>



          <div class="row">
            <div class="col-lg-8 mx-auto">

              <p>Posts, and, government picture with time feedback. His generally, in to be didn't in cannot on was his get clarinet of let with shoulders either the for her nations this out up posterity continued likely an phase by were named negatives, reached the school thought, escape, spread back rather the world; We claim a should in material into profiles.</p>

              <ul>
                <li>Energistically coordinate business relationships</li>
                <li>Change via resource-leveling innovation</li>
                <li>Efficiently develop fully researched experiences and integrated</li>
                <li>Assertively empower customized alignments go forward vortals</li>
              </ul>

              <p>Viewings italic, the time. Them. The in lady that. So copy the founded, sovereignty. Big have each have stick clarinet based motors himself isn't authentic of embarkation and when a needs to where supplies a in their my on bread unavoidable, follow the thought, two of the in phase downstairs the tower, a been is good there systems of eye or a was. Is being at carefully the to never who even contract, to than all its mountains, with associate rational to films it or long of if detailed in the state.</p>

              <blockquote class="blockquote">
                <div class="quote-sign"></div>
                <p>On feedback the can likewise, in problem at was. I regretting for rationalize time, so language it to would legs ports, the tone it different alarm four.</p>
                <footer>Bryant Wells in <cite title="Onemar Associates Inc.">Onemar Associates Inc.</cite></footer>
              </blockquote>

              <p>With as characters right and up of eating how a and area or only objective apparent on coordinates the result, watching to do some such she was she customary the sooner a to by from at were, packed have was stuffed funny concept? He origin be his her aggressively having to may me remain and the still poured and by the for come important. Of at survey left to occupied has a downstairs and felt compared concept? Off would help the was the to and to them hologram have agreed not seal luxury their found which from the manage change.</p>

              <div class="gap-xy-2 mt-6">
                <a class="badge badge-pill badge-secondary" href="#">Record</a>
                <a class="badge badge-pill badge-secondary" href="#">Progress</a>
                <a class="badge badge-pill badge-secondary" href="#">Customers</a>
                <a class="badge badge-pill badge-secondary" href="#">News</a>
              </div>

            </div>
          </div>


        </div>
      </div>



      <!--
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      | Comments
      |‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
      !-->
      <div class="section bg-gray">
        <div class="container">

          <div class="row">
            <div class="col-lg-8 mx-auto">

              <div class="media-list">

                <div class="media">
                  <img class="avatar avatar-sm mr-4" src="{% static '/assets/img/avatar/1.jpg' %}" alt="...">

                  <div class="media-body">
                    <div class="small-1">
                      <strong>Maryam Amiri</strong>
                      <time class="ml-4 opacity-70 small-3" datetime="2018-07-14 20:00">24 min ago</time>
                    </div>
                    <p class="small-2 mb-0">Thoughts his tend and both it fully to would the their reached drew project the be I hardly just tried constructing I his wonder, that his software and need out where didn't the counter productive.</p>
                  </div>
                </div>



                <div class="media">
                  <img class="avatar avatar-sm mr-4" src="{% static '/assets/img/avatar/2.jpg' %}" alt="...">

                  <div class="media-body">
                    <div class="small-1">
                      <strong>Hossein Shams</strong>
                      <time class="ml-4 opacity-70 small-3" datetime="2018-07-14 20:00">6 hours ago</time>
                    </div>
                    <p class="small-2 mb-0">Was my suppliers, has concept how few everything task music.</p>
                  </div>
                </div>



                <div class="media">
                  <img class="avatar avatar-sm mr-4" src="{% static '/assets/img/avatar/3.jpg' %}" alt="...">

                  <div class="media-body">
                    <div class="small-1">
                      <strong>Sarah Hanks</strong>
                      <time class="ml-4 opacity-70 small-3" datetime="2018-07-14 20:00">Yesterday</time>
                    </div>
                    <p class="small-2 mb-0">Been me have the no a themselves, agency, it that if conduct, posts, another who to assistant done rattling forth there the customary imitation.</p>
                  </div>
                </div>

              </div>


              <hr>


              <form action="#" method="POST">

                <div class="row">
                  <div class="form-group col-12 col-md-6">
                    <input class="form-control" type="text" placeholder="Name">
                  </div>

                  <div class="form-group col-12 col-md-6">
                    <input class="form-control" type="text" placeholder="Email">
                  </div>
                </div>

                <div class="form-group">
                  <textarea class="form-control" placeholder="Comment" rows="4"></textarea>
                </div>

                <button class="btn btn-primary btn-block" type="submit">Submit your comment</button>
              </form>

            </div>
          </div>

        </div>
      </div>



    </main>


{% endblock %}

article/templates/articles.html
{% extends "layout.html" %}
{% load static %}
{% block content %}


    <!-- Header -->
    <header class="header text-center text-white" style="background-image: linear-gradient(-225deg, #5D9FFF 0%, #B8DCFF 48%, #6BBBFF 100%);">
      <div class="container">

        <div class="row">
          <div class="col-md-8 mx-auto">

            <h1>Güncel Makaleler</h1>
            <p class="lead-2 opacity-90 mt-6">Read and get updated on how we progress</p>

          </div>
        </div>

      </div>
    </header><!-- /.header -->


    <!-- Main Content -->
    <main class="main-content">
      <div class="section bg-gray">
        <div class="container">
          <div class="row">


            <div class="col-md-8 col-xl-9">
              <div class="row gap-y">

                {% for article in makale %}
                  <div class="col-md-6" >
                    <div class="card border hover-shadow-6 mb-6 d-block">
                      <a href="{% url 'article_detail' articleslug=article.article_slug %}"><img class="card-img-top" src="{% static '/assets/img/thumb/17.jpg' %}" alt="Card image cap"></a>
                      <div class="p-6 text-center">
                        <p><a class="small-5 text-lighter text-uppercase ls-2 fw-400" href="#">News</a></p>
                        <h5 class="mb-0"><a class="text-dark" href="#">{{ article.title }}</a></h5>
                      </div>
                    </div>
                  </div>
                {% endfor %}

                <div class="pagination">
                  <span class="step-links">
                    {% if makale.has_previous %}
                    <div class="btn btn-warning">
                      <a href="?page=1">&laquo; first </a>
                      </div>
                      <div class="btn btn-warning">
                        <a href="?page={{ makale.previous_page_number }}">previous</a>
                      </div>



                    {% endif %}

                    {% for i in makale.paginator.page_range %}

                         {% if forloop.counter < 5 %}
                         <div class="btn btn-warning ">
                           <a class="page-numbers {% if i == makale.number %}current{% endif %}" href="?page={{forloop.counter}}">{{forloop.counter}}</a>
                         </div>

                         {% endif %}

                     {% endfor %}

                    {% if makale.has_next %}
                    <div class="btn btn-warning">
                      <a href="?page={{ makale.next_page_number }}">next</a>
                      </div>
                      <div class="btn btn-warning" >
                        <a href="?page={{ makale.paginator.num_pages }}">last &raquo;</a>
                      </div>



                    {% endif %}
                  </span>
                </div>








        </div>
      </div>
    </main>




{% endblock %}

article/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <title>Kurumsaly</title>

    <!-- Styles -->
    <link href="{% static 'assets/css/page.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'assets/img/favicon.png' %}">
  </head>

  <body data-spy="scroll" data-target=".nav-navbar" data-offset="100">


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-stick-dark" data-navbar="smart">
      <div class="container">

        <div class="navbar-left">
          <button class="navbar-toggler" type="button">&#9776;</button>
          <a class="navbar-brand" href="#">
            <img class="logo-dark" src="{% static '/assets/img/logo-dark.png' %}" alt="logo">
            <img class="logo-light" src="{% static '/assets/img/logo-light.png' %}" alt="logo">
          </a>
        </div>

        <section class="navbar-mobile">
          <nav class="nav nav-navbar ml-auto">
            <a class="nav-link active" href="{% url 'article:index' %}">Anasayfa</a>
            <a class="nav-link" href="#features">Hizmetlerimiz</a>
            <a class="nav-link" href="#experts">Uzmanlarımız</a>
            <a class="nav-link" href="#contact">İletişim</a>
          </nav>
        </section>

      </div>
    </nav><!-- /.navbar -->



    {% block content %}

    {% endblock %}


    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="row gap-y align-items-center">

          <div class="col-6 col-lg-3">
            <a href="../index.html"><img src="{% static '/assets/img/logo-dark.png' %}" alt="logo"></a>
          </div>

          <div class="col-6 col-lg-3 text-right order-lg-last">
            <div class="social">
              <a class="social-facebook" href="https://www.facebook.com/thethemeio"><i class="fa fa-facebook"></i></a>
              <a class="social-twitter" href="https://twitter.com/thethemeio"><i class="fa fa-twitter"></i></a>
              <a class="social-instagram" href="https://www.instagram.com/thethemeio/"><i class="fa fa-instagram"></i></a>
              <a class="social-dribbble" href="https://dribbble.com/thethemeio"><i class="fa fa-dribbble"></i></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="nav nav-bold nav-uppercase nav-trim justify-content-lg-center">
              <a class="nav-link" href="{% url 'article:index' %}">Anasayfa</a>
              <a class="nav-link" href="{% url 'article:about' %}">Hakkımızda</a>
              <a class="nav-link" href="{% url 'article:articles' %}">Blog</a>
              <a class="nav-link" href="../page/contact-1.html">İletişim</a>
            </div>
          </div>

        </div>
      </div>
    </footer><!-- /.footer -->


    <!-- Scroll top -->
    <button class="btn btn-circle btn-primary scroll-top"><i class="fa fa-angle-up"></i></button>


    <!-- Scripts -->
    <script src="{% static '/assets/js/page.min.js' %}"></script>
    <script src="{% static '/assets/js/script.js' %}"></script>

  </body>
</html>

templates/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <title>Kurumsaly</title>

    <!-- Styles -->
    <link href="{% static 'assets/css/page.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'assets/img/favicon.png' %}">
  </head>

  <body data-spy="scroll" data-target=".nav-navbar" data-offset="100">


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-stick-dark" data-navbar="smart">
      <div class="container">

        <div class="navbar-left">
          <button class="navbar-toggler" type="button">&#9776;</button>
          <a class="navbar-brand" href="#">
            <img class="logo-dark" src="{% static '/assets/img/logo-dark.png' %}" alt="logo">
            <img class="logo-light" src="{% static '/assets/img/logo-light.png' %}" alt="logo">
          </a>
        </div>

        <section class="navbar-mobile">
          <nav class="nav nav-navbar ml-auto">
            <a class="nav-link active" href="#home">Anasayfa</a>
            <a class="nav-link" href="#features">Hizmetlerimiz</a>
            <a class="nav-link" href="#experts">Uzmanlarımız</a>
            <a class="nav-link" href="#contact">İletişim</a>
          </nav>
        </section>

      </div>
    </nav><!-- /.navbar -->



    {% block content %}

    {% endblock %}


    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="row gap-y align-items-center">

          <div class="col-6 col-lg-3">
            <a href="../index.html"><img src="{% static '/assets/img/logo-dark.png' %}" alt="logo"></a>
          </div>

          <div class="col-6 col-lg-3 text-right order-lg-last">
            <div class="social">
              <a class="social-facebook" href="https://www.facebook.com/thethemeio"><i class="fa fa-facebook"></i></a>
              <a class="social-twitter" href="https://twitter.com/thethemeio"><i class="fa fa-twitter"></i></a>
              <a class="social-instagram" href="https://www.instagram.com/thethemeio/"><i class="fa fa-instagram"></i></a>
              <a class="social-dribbble" href="https://dribbble.com/thethemeio"><i class="fa fa-dribbble"></i></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="nav nav-bold nav-uppercase nav-trim justify-content-lg-center">
              <a class="nav-link" href="">Anasayfa</a>
              <a class="nav-link" href="/about/">Hakkımızda</a>
              <a class="nav-link" href="../blog/grid.html">Blog</a>
              <a class="nav-link" href="../page/contact-1.html">İletişim</a>
            </div>
          </div>

        </div>
      </div>
    </footer><!-- /.footer -->


    <!-- Scroll top -->
    <button class="btn btn-circle btn-primary scroll-top"><i class="fa fa-angle-up"></i></button>


    <!-- Scripts -->
    <script src="{% static '/assets/js/page.min.js' %}"></script>
    <script src="{% static '/assets/js/script.js' %}"></script>

  </body>
</html>